### ISSUE TITLE
Recursively search for the config in parent directories

### ISSUE THREAD

**Issue by Natoandro** [zifeo/whiz#7]

**Comment by afmika** [comment]
I don't really understand, by "parent directories" what does that mean exactly mean ?
Suppose whiz's binary is located at `/one/two/three/whiz_root` then I do `cd ./four/five`.
Where do we start ? 
1. From `/one/two/three/whiz_root` ?
2. From `/one/two/three/whiz_root/four/five` ?

**Comment by Natoandro** [comment]
Suppose we have this folder structure:
```
app/
    src/
        main.rs
        utils/
            mod.rs
    whiz.yaml
```

I we run `whiz` when we are at `app/src/utils/` (working directory), we have an error: `file error: file whiz.yaml not found`.

The idea is to search for `whiz.yaml` in `app/src/` and then `app/`, and ... so on, until it finds `whiz.yaml` or `whiz.yml`, and use that file as the config, and the directory as the root directory.

**Comment by afmika** [comment]
So the working directory takes priority over the binary location if my understanding is correct.
Then I simply need to backtrack the path till I find a `whiz.yaml` starting from the working directory (inclusive).

**Comment by Natoandro** [comment]
> So the working directory takes priority over the binary location if my understanding is correct. Then I simply need to backtrack the path till I find a `whiz.yaml` starting from the working directory (inclusive).

What binary are you talking about?

**Comment by afmika** [comment]
> > So the working directory takes priority over the binary location if my understanding is correct. Then I simply need to backtrack the path till I find a `whiz.yaml` starting from the working directory (inclusive).
> 
> What binary are you talking about?

The executable we get after a build

**Comment by Natoandro** [comment]
I think the location of the whiz's binary is never taken into account. Is it?

**Comment by afmika** [comment]
> I think the location of the whiz's binary is never taken into account. Is it?

It was not mentioned anywhere although a bit implied hence my question as I could see a use case in which I'd use the binary location as a default search path.
